services:
  postgres:
    image: postgres:16-alpine
    container_name: elishop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: elishop_admin
      POSTGRES_PASSWORD: elishop2026
      POSTGRES_DB: elishop_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - elishop_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U elishop_admin -d elishop_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elishop-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: elishop_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elishop.ec
      PGADMIN_DEFAULT_PASSWORD: admin2026
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - elishop-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: elishop_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      # Conecta al servicio 'postgres' en lugar de localhost
      DATABASE_URL: postgresql://elishop_admin:elishop2026@postgres:5432/elishop_db
      JWT_SECRET: elishop-jwt-secret-2026-super-secure-key
      JWT_EXPIRATION: 7d
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - elishop-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: elishop_frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - elishop-network

volumes:
  elishop_postgres_data:


networks:
  elishop-network:
    driver: bridge
